######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 8 09:53:40 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += censusimage.cpp \
    censuscorrelation.cpp \
    stereo.cpp \
    main.cpp

HEADERS += \
    util.h \
    censusimage.h \
    censuscorrelation.h \
    stereo.h \
    correlation.h \
    matchingtable.h
